FROM espnet/espnet:cpu-latest
# FROM espnet/espnet:gpu-latest
USER root

WORKDIR /espdocker/

COPY . /espdocker/

RUN pip install -r requirements.txt


# EXPOSE 8888
ENV PYTHON_VERSION=3.11.7

# Download and install Python from source

# Start the Jupyter Notebook server
# CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--no-browser", "--allow-root"]

CMD ["/bin/bash"]